### ISSUE TITLE
kvv2 secret engine

### ISSUE THREAD

**Issue by angelo-wm** [hashicorp/vault-k8s#100]
Hello, I am trying to adapt the example project/ helm charts to our environment which involves an external vault server running a kvV2 secret engine and is also namespaced. Would it be possible to show an example in such a case? Or help with addressing an issue where the init pod fails with:

2020/03/02 18:43:22.139919 [WARN] vault.read(namespace_name/secret/data/folder/secret): failed to check if namespace_name/secret/data/folder/secret is KVv2, assume not: Error making API request.

URL: GET https://vault.host.address:8200/v1/sys/internal/ui/mounts/namespace_name/secret/data/folder/secrett
Code: 403. Errors:

* preflight capability check returned 403, please ensure client's policies grant access to path "namespace_name/secret/data/folder/secret"

**Comment by nxtof** [comment]
I'm experimenting the same issue, even if I set the policy associated to the service account under  which the pod is running to something very permissive like:

```
vault policy write myapp-policy - <<EOF
    path "sys/*" {
      capabilities = ["read", "list"]
    }
    path "secret/*" {
      capabilities = ["read", "list"]
    }
    path "secrets/*" {
      capabilities = ["read", "list"]
    }
EOF
```

**Comment by nxtof** [comment]
Helm chart version: v0.4.0
Vault server version: v1.3.2
Sample secret I'm trying to reach was created using Terraform:

```terraform
resource "vault_generic_secret" "samplesecret" {
  path = "secret/myapp/test"
  data_json = <<EOT
  {
    "value": "mysecret"
  }
  EOT
}

```

**Comment by angelo-wm** [comment]
It appears that this issue was fixed for me with the addition of namespace support given: https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#030-march-5th-2020

**Comment by nxtof** [comment]
Still having the same issue with the latest release 0.3.0.

@angelo-wm did you use any specific new flag/feature?

**Comment by angelo-wm** [comment]
I utilized the  vault.hashicorp.com/namespace flag and then removed the namespace from my auth and secret paths

**Comment by jasonodonnell** [comment]
Closing as original issue has been resolved!
