### ISSUE TITLE
x509  error when trying to use secret-volume-path

### ISSUE THREAD

**Issue by NMamont** [hashicorp/vault-k8s#104]
I tried adding custom mount path for my secrets, but when i add `vault.hashicorp.com/secret-volume-path` i  have error with authenticating with my external vault server.
If removed this annotation all works fine.
My pod annotations:

```       vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/secret-volume-path: "/etc/ssl/certs"
        # TLS SERVER CERTIFICATE
        vault.hashicorp.com/agent-inject-secret-server.cert: "test-int-ca/issue/test-client"
        vault.hashicorp.com/agent-inject-template-server.cert: |
          {{- with secret "test-int-ca/issue/test-client" "common_name=test.clients.test.acme.com" -}}
          {{ .Data.certificate }}
          {{- end }}
        # TLS SERVER KEY
        vault.hashicorp.com/agent-inject-secret-server.key: "test-int-ca/issue/test-client"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "test-int-ca/issue/test-client" "common_name=test.clients.test.acme.com" -}}
          {{ .Data.private_key }}
        vault.hashicorp.com/role: 'pkitest'
        vault.hashicorp.com/auth-path: 'auth/authpath'
          {{- end }}
```

Logs from init container:

```
==> Vault server started! Log data will stream in below:

2020-03-11T07:46:10.538Z [INFO]  sink.file: creating file sink
2020-03-11T07:46:10.538Z [INFO]  sink.file: file sink configured: path=/home/vault/.vault-token mode=-rw-r-----
2020-03-11T07:46:10.538Z [INFO]  auth.handler: starting auth handler
2020-03-11T07:46:10.538Z [INFO]  template.server: starting template server
2020-03-11T07:46:10.538Z [INFO]  auth.handler: authenticating
2020/03/11 07:46:10.538592 [INFO] (runner) creating new runner (dry: false, once: false)
2020-03-11T07:46:10.538Z [INFO]  sink.server: starting sink server
2020/03/11 07:46:10.539179 [INFO] (runner) creating watcher
==> Vault agent configuration:

                     Cgo: disabled
               Log Level: info
                 Version: Vault v1.3.1

2020-03-11T07:46:10.559Z [ERROR] auth.handler: error authenticating: error="Put https://vault.my-company.com/v1/auth/authpath/login: x509: certificate signed by unknown authority" backoff=2.5705917339999997
2020-03-11T07:46:13.130Z [INFO]  auth.handler: authenticating
2020-03-11T07:46:13.143Z [ERROR] auth.handler: error authenticating: error="Put https://vault.my-company.com/v1/auth/authpath/login: x509: certificate signed by unknown authority" backoff=1.091042295
```

**Comment by NMamont** [comment]
UPD: I added annotation `vault.hashicorp.com/tls-skip-verify: 'true'` and it's worked, but what is the relationship between annotation and certificate? Vault server has correct ssl by lets'encrypt, so i don't need фтн additional CA cert for verification

**Comment by GuillaumeKG** [comment]
You need to add the let s encrypt CAs to your application.
Indeed, the let s encrypt certificates are signed by an CA known by the browsers.   
However in your case it seems you are in a app to app communication scenario.  
So, if you don t want to skip the tls check, your application needs to have the let s encrypt CA to validate the certificate of your vault.
https://letsencrypt.org/fr/certificates/

**Comment by jasonodonnell** [comment]
@NMamont The Vault client is connecting to Vault which is protected with TLS.  The client doesn't just trust the server's certificate authenticity, so it needs to have the CA certificate that the server certificates were signed to double check.  Simply add the CA certificate used to sign Vault servers certificates.  You can see an example of the annotations here: https://www.vaultproject.io/docs/platform/k8s/injector/examples/#patching-existing-pods (note: this uses client certs as well for mTLS, where the server also verifies the authenticity of the _clients_ certs, but isn't strictly needed if you aren't enforcing client certs).
