### ISSUE TITLE
secret-volume-path not rendering secrets in desired path

### ISSUE THREAD

**Issue by samgabrail** [hashicorp/vault-k8s#105]
I'm trying to inject secrets onto a specific folder in my container: /app/env

I'm using the vault.hashicorp.com/secret-volume-path annotation as per:
https://www.vaultproject.io/docs/platform/k8s/injector/annotations/#inlinecode-vaulthashicorpcomsecret-volume-path

I still see my secrets show up under /vault/secrets/

Is this not the right way to use it?

This is what I have as an annotation:
```
vault.hashicorp.com/secret-volume-path: "/app/env/"
```

**Comment by ToxicWar** [comment]
@samgabrail Do you use 0.3.0 version of `vault-k8s`?

https://github.com/hashicorp/vault-k8s/pull/99

**Comment by samgabrail** [comment]
@ToxicWar  that was my issue. I had upgraded the helm chart but the image for the injector in the values.yaml file was older. I updated it to 0.3.0 and now it works great. Thanks a lot!
