### ISSUE TITLE
Injected sidecar is not using the configure authPath from Sidecar injector deployment

### ISSUE THREAD

**Issue by carlosjgp** [hashicorp/vault-k8s#106]
Sidecar injector deployed using Vault-helm chart
https://github.com/hashicorp/vault-helm/blob/master/templates/injector-deployment.yaml#L49

```
injector.authPath=auth/eks-ci
```

but the injected sidecar is using
```
auth/kubernetes
```
instead

**Comment by bisi1** [comment]
@carlosjgp How did you fix this issue?

**Comment by carlosjgp** [comment]
Yes! @bisi1 

After upgrading to the latest release of the chart the problem got solved

Thanks!
