### ISSUE TITLE
Will the Mutating Webhook only deal with Pods?

### ISSUE THREAD

**Issue by pauldthomson** [hashicorp/vault-k8s#109]
I noticed that the webhook is configured to watch `deployments`, `pods`, `statefulsets` and `jobs`, but actually only handles `pods` just now (unless I don't understand how the AdmissionRequest works). Are there plans to change this in the future?

If I had an Operator that was creating pods, and wanted to add annotations directly to the pod to get the Vault agent injected, it _seems_ like it will work just now, but since the documentation mentions annotating the `Deployment` (albeit in the pod template spec), I'm wondering if this will change in the future and only work off of `Deployment`s

**Comment by jasonodonnell** [comment]
We only work with pods and as you've noticed, we're making changes to pod spec within the controller objects (deployments, statefulsets, jobs etc).
