### ISSUE TITLE
AKS Vault agent Injector annotations-patches are not updating /vaults/secrets

### ISSUE THREAD

**Issue by woowil** [hashicorp/vault-k8s#114]
I'm using Vault-Helm chart to deploy Vault on Azure Kubernetes Services. 

I have created an issuer on the Vault-helm repo with detailed information. I assume this problem is partly related to the injector image and admission webhook. 

Any suggestions, please?

https://github.com/hashicorp/vault-helm/issues/244

**Comment by tvoran** [comment]
Closing, duplicate of https://github.com/hashicorp/vault-helm/issues/244
