### ISSUE TITLE
[Feature] Allow altering consul template for default secret output

### ISSUE THREAD

**Issue by kennethtxytqw** [hashicorp/vault-k8s#116]
Hi Vault mavericks!

I like to be able to change the default output format at the cluster level. I did not see such an option, if there is can you please direct me to it?

Thank you.

**Comment by jasonodonnell** [comment]
Hi @kennethtxytqw, there's currently no way to override the default template at the cluster level.  This would be a good feature to have though, so I'll keep this open and mark it as an enhancement we can make.

If the community wants to tackle this feature, please let us know!
