### ISSUE TITLE
Injector never complete

### ISSUE THREAD

**Issue by tzahimizrahi** [hashicorp/vault-k8s#120]
I installed vault k8s from the helm chart. Now I trying implement the injector in a batch jobs and I'm facing with the issue that the injectors container never complete so the pod remain up untill I deleted it.
Any solution or workaround for batch jobs use case?

**Comment by itisevgeny** [comment]
@tzahimizrahi , 
Have you tried vault.hashicorp.com/agent-pre-populate-only annotation?

**Comment by jasonodonnell** [comment]
Hi @tzahimizrahi, @itisevgeny is correct, you should disable the runtime Vault Agent container and only use the init container by setting the annotation: `vault.hashicorp.com/agent-pre-populate-only: true`

**Comment by tzahimizrahi** [comment]
Yup that's working for me
Thanks
