### ISSUE TITLE
Raw binaries 

### ISSUE THREAD

**Issue by n-ik** [hashicorp/vault-k8s#122]
Hello, I wanted to build a Docker Image. Unfortunately there seems to be no binaries available at https://releases.hashicorp.com/vault-k8s/.

Has the location changed?

**Comment by jasonodonnell** [comment]
Hi @n-ik !

Our official CI pipeline was recently completed but we have no done a release using the pipeline.  Unfortunately only new binary releases will be available on releases.hashicorp.com starting with the next Vault K8s release.  Hope that helps.

**Comment by samuanv** [comment]
Hello @jasonodonnell,

I was looking to do a few tweaks to try AppRole authentication.

Does that mean that we cannot build a modified image until you do a new release?
If so,When are you planning to do this release?

Is there any other way to get the latest binary to build test images?

Thank you
