### ISSUE TITLE
auto restart pod after secret update

### ISSUE THREAD

**Issue by Nikitossh** [hashicorp/vault-k8s#127]
First of all I wish to ask you: thank you for a great tool! It is very interesting and useful. But I have a
 question. I created secret in vault UI, added it to k8s deployment via annotations and can see it in /vault/secrets/application.yml in my pod. This is config for my app.
My app is running with this config, all is OK, and now I want to change something in config. I create new version for secret in vault UI, edit it and put save..... After ~4 minutes I can see that config was changed. But to apply this config I have to restart pods by hand.
 
Is it any way to automatically restart pods after secret was updated?

**Comment by carlosjgp** [comment]
That's normally done through another sidebar container that watches for files changes and hit a rest endpoint to force the app on the "main" container to reload the configuration/secret

You can see this pattern on Prometheus and Grafana Helm charts for example

Kubernetes and, in this case, Vault agent delegate the responsibility of handling reloading to the app/developer

Other approaches are Stakater reloader or even a not Kubernetes aware approach like Spring Cloud Config server

I hope that helps!

**Comment by Nikitossh** [comment]
Thanks a lot for the answer!
