### ISSUE TITLE
Render consul values

### ISSUE THREAD

**Issue by rmgpinto** [hashicorp/vault-k8s#128]
Can consul kv values be rendered with vault-k8s?

The idea is to use the kubernetes auth method to authenticate to vault and get a consul token that is used to authenticate to consul and render kv values.
Since this project uses consul-template, it's a nice to have feature.

**Comment by pcman312** [comment]
Thanks for opening this issue!

Rendering consul values is not currently supported as the templating only talks to Vault. I'll confer with the team to see if this is something that we can support.

**Comment by pcman312** [comment]
After conferring with the team, this is not something we are able to support at this time.

**Comment by rmgpinto** [comment]
Thanks, we solved it by forking this repo and adding the necessary code changes.

**Comment by schmurfy** [comment]
@rmgpinto could you share your changes ?
I am also interested in doing this and curious about the approach you chose
