### ISSUE TITLE
Vault injector not working with Vault Namespaces

### ISSUE THREAD

**Issue by JoshStead** [hashicorp/vault-k8s#129]
Hello

I have deployed the vault injector into OpenShift 4.3 but when triggering the sidecar to inject a kv secret it does not work. The secret is stored inside a vault namespace which i think is where my issue is. 

I have tried this with and without vault.hashicorp.com/namespace annotation and i get different error messages.

```
annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-openshift.txt: secrets/data/openshift
        vault.hashicorp.com/log-level: debug
        vault.hashicorp.com/role: testk8s
        vault.hashicorp.com/tls-skip-verify: 'true'
```
these annotations gives me

```
2020/04/28 09:30:51.589964 [WARN] (view) vault.read(secrets/data/openshift): no secret exists at secrets/data/openshift (retry attempt 1 after "250ms")
2020-04-28T09:30:51.649Z [INFO]  auth.handler: renewed auth token
2020/04/28 09:30:51.873498 [WARN] (view) vault.read(secrets/data/openshift): no secret exists at secrets/data/openshift (retry attempt 2 after "500ms")
```

```
annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-openshift.txt: secrets/data/openshift
        vault.hashicorp.com/log-level: debug
        vault.hashicorp.com/namespace: namespaceX
        vault.hashicorp.com/role: testk8s
        vault.hashicorp.com/tls-skip-verify: 'true'
```

these annotations gives me

```
2020/04/28 09:32:27.268666 [INFO] (runner) creating watcher
2020-04-28T09:32:27.305Z [ERROR] auth.handler: error authenticating: error="Error making API request.

URL: PUT https://vault.domain:8200/v1/namespaceX/auth/kubernetes/login
Code: 400. Errors:

* missing client token" backoff=1.737271052
2020-04-28T09:32:29.042Z [INFO]  auth.handler: authenticating
2020-04-28T09:32:29.069Z [ERROR] auth.handler: error authenticating: error="Error making API request.

URL: PUT https://vault.domain:8200/v1/namespaceX/auth/kubernetes/login
Code: 400. Errors:

* missing client token" backoff=2.922598087
```

I have manually tested that the OpenShift service account can authenticate with vault (and receive a token) and the service account can also retrieve a kv secret from the command line so I believe it has the correct permissions

Setup:
External Vault using namespaces
Vault Injector deployed from https://github.com/openlab-red/hashicorp-vault-for-openshift as per https://github.com/hashicorp/vault-k8s/issues/59
OpenShift 4.3.10

Any Ideas?

**Comment by tvoran** [comment]
Just to double check, is the kubernetes auth backend enabled and configured under the namespace? i.e.

```shell
vault auth enable -namespace namespaceX kubernetes
vault write -namespace education auth/kubernetes/config ...
...
```

I get that error if kubernetes auth is enabled on the root, but not on the namespace.

**Comment by JoshStead** [comment]
Hi @tvoran 

This resolved our issue, we recreated the Kubernetes Auth with the -namespace and now we can inject the credential into the pod :). 

Many Thanks 👍

**Comment by tvoran** [comment]
Great! Glad that worked.
