### ISSUE TITLE
Mutating Webhooks works only if new pod is created in "hashicorp" namespace.

### ISSUE THREAD

**Issue by sohamshahmoodys** [hashicorp/vault-k8s#139]
Mutating Webhooks works only if new pod is created in "hashicorp" namespace.
vault injector pod is running within "hashicorp" namespace. If application pod with required vault annotations is triggered from "hashicorp" namespace then it works fine and vault-agent-init container is created.

But if request is created from any other namespace except "hashicorp", vault-agent-init container is not created. As mentioned in the example, "vault.hashicorp.com/agent-webhook" label is added to the namespace.

Vault Injector pod gives below error.
2020/05/29 04:20:52 http: panic serving 10.29.128.1:53600: runtime error: invalid memory address or nil pointer dereference
goroutine 56 [running]:
net/http.(*conn).serve.func1(0xc0002780a0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1111380, 0x1c04cf0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/hashicorp/vault-k8s/agent-inject/agent.Init(0xc000099180, 0xc000042049, 0xb, 0xc00003e068, 0x2a, 0x1267c73, 0xf, 0xc0002609d0, 0x9, 0x0, ...)
	/Users/mmascia/dev/lab/go/src/github.com/hashicorp/vault-k8s/agent-inject/agent/annotations.go:253 +0x550
github.com/hashicorp/vault-k8s/agent-inject.(*Handler).Mutate(0xc0002ad500, 0xc000578c60, 0xa1f)
	/Users/mmascia/dev/lab/go/src/github.com/hashicorp/vault-k8s/agent-inject/handler.go:151 +0x83f
github.com/hashicorp/vault-k8s/agent-inject.(*Handler).Handle(0xc0002ad500, 0x1408d20, 0xc0001540e0, 0xc0003fa500)
	/Users/mmascia/dev/lab/go/src/github.com/hashicorp/vault-k8s/agent-inject/handler.go:87 +0x721
net/http.HandlerFunc.ServeHTTP(0xc000284ca0, 0x1408d20, 0xc0001540e0, 0xc0003fa500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0002c0480, 0x1408d20, 0xc0001540e0, 0xc0003fa500)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000154d20, 0x1408d20, 0xc0001540e0, 0xc0003fa500)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0002780a0, 0x140c360, 0xc00032a280)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384

**Comment by tvoran** [comment]
Hi @sohamshahmoodys can you provide more information about the configuration you're using? Specifically the values settings that are in use.
