### ISSUE TITLE
Concatenate rendered templates to one file

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault-k8s#148]
Hi Guys, 
I'm not sure to what projects it's better to report - consul-template, vault, or vault-k8s, please correct if I'm wrong. 

As mentioned in title I'm looking for a reliable way of concatenating several rendered templates and write those to one file. 
One of my use-cases is to create AWS credential file with several profiles.
```yaml
vault.hashicorp.com/agent-inject-secret-aws: aws-account_1/creds/my-role
vault.hashicorp.com/agent-inject-template-aws: |
  {{ with secret "aws-account1/creds/my-role" -}}
  [account_1]
  aws_access_key_id     = {{ .Data.access_key }}
  aws_secret_access_key = {{ .Data.secret_key }}
  {{ end -}}
vault.hashicorp.com/agent-inject-secret-aws: aws-account_2/creds/my-role
vault.hashicorp.com/agent-inject-template-aws: |
  {{ with secret "aws-account_2/creds/my-role" -}}
  [account_2]
  aws_access_key_id     = {{ .Data.access_key }}
  aws_secret_access_key = {{ .Data.secret_key }}
  {{ end -}}
```

What to have something like **/vault/secret/aws**:
```
[account_1]
  aws_access_key_id     = XXXX1
  aws_secret_access_key = YYYY1
[account_2]
  aws_access_key_id     = XXXX2
  aws_secret_access_key = YYYY2
```
Seems current behavior is overwriting `/vault/secret/aws` file with the last template.  Is there any way to concatenate, append both of them?  

I'd like to avoid using the **command** for this, as both AWS Secret Engine have similar TTL and I'm afraid unclear results here.  

Thanks.

**Comment by iusergii** [comment]
I'm assuming that appending rendered string to file will actually break profile structure.

**Comment by jasonodonnell** [comment]
Hi @iusergii, I wonder if this would work?

```
vault.hashicorp.com/agent-inject-secret-aws: aws-account_1/creds/my-role
vault.hashicorp.com/agent-inject-template-aws: |
  {{ with secret "aws-account1/creds/my-role" -}}
  [account_1]
  aws_access_key_id     = {{ .Data.access_key }}
  aws_secret_access_key = {{ .Data.secret_key }}
  {{ end -}}
  {{ with secret "aws-account_2/creds/my-role" -}}
  [account_2]
  aws_access_key_id     = {{ .Data.access_key }}
  aws_secret_access_key = {{ .Data.secret_key }}
  {{ end -}}
```

**Comment by iusergii** [comment]
Hi @jasonodonnell , thanks for the example.  I didn't expect it possible to have more than one dynamic secrets in one template.  
It works.
Since AWS User keys are eventually consistent I guess I need some timeout for rendering. Currently, I'm using "**command**" with `sleep 10`. Is there any plan to support [wait](https://www.vaultproject.io/docs/agent/template#wait)

**Comment by jasonodonnell** [comment]
I think we can support wait, it should be pretty easy to add.  Not sure when we can get it in but we'll take a look!

**Comment by iusergii** [comment]
Cool. Thanks @jasonodonnell , closing this ticket.
