### ISSUE TITLE
Inject all secrets from vault KV engine

### ISSUE THREAD

**Issue by nagesh-salunke** [hashicorp/vault-k8s#157]
I have been able to inject a specific secret with annotation

```
vault.hashicorp.com/agent-inject-secret-<secret-name>
```

I have a use case where there are multiple(15-20) secrets into one KV engine in vault and I want all of them to be injected to the pod and have a common template for all of them

One possibility of injecting all of them is to provide those many annotations for all the named secrets

I checked annotation document [here](https://www.vaultproject.io/docs/platform/k8s/injector/annotations
) and couldn't find a way to do this with minimal configuration.

Are there any other alternatives than repeating the annotation for all secret ?   
If no, are there any plans for supporting such use case ?

Thanks

**Comment by tvoran** [comment]
Since the injector is using consul-template, you should be able to use the secrets directive to dump all the secrets: https://github.com/hashicorp/consul-template#secrets

**Comment by nagesh-salunke** [comment]
Thanks,   
I was able to get with minimal config code by using consul template like below to generate annotations

```
        {{- $root := . -}}
         {{- range $i, $envprop := .Values.secret.services}}
         {{`vault.hashicorp.com/agent-inject-secret-`}}{{ $envprop.key }}{{`-`}}{{ $root.Values.profile }}{{`.properties: "secret/`}}{{ $envprop.key }}{{`-`}}{{ $root.Values.profile }}"
         {{`vault.hashicorp.com/agent-inject-template-`}}{{ $envprop.key }}{{`-`}}{{ $root.Values.profile }}.properties: |
            {{`{{ with secret "secret/`}}{{ $envprop.key }}{{`-`}}{{ $root.Values.profile }}"{{` }}
            {{ range $k, $v := .Data.data }}
            {{ $k }}={{ $v }}
            {{ end }}
            {{ end }}`}}
         {{- end}}
```
