### ISSUE TITLE
Custom Vault agent container resource defaults

### ISSUE THREAD

**Issue by luke-dd** [hashicorp/vault-k8s#166]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to specify default resource values for Vault Agent containers created by the agent-injector webhook. These defaults have fixed values and can only be overridden via annotations on the resource being mutated.

**Describe the solution you'd like**
It would be useful to be able to provide default resource requests/limits that will apply to Vault Agent init/sidecar containers added to pods via the webhook. These defaults could then be specified in the [agent-injector Helm chart](https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L26).

**Describe alternatives you've considered**
For now, using the `vault.hashicorp.com/agent-requests-`/`vault.hashicorp.com/agent-limits-` annotations per deployment works, but it would be helpful to be able to move this configuration to the agent-injector.

**Comment by sarahhenkens** [comment]
It would also be nice if we could disable the resources altogether. At least have the option to do it 🤔

**Comment by jasoares** [comment]
+1 for this. Looking for the same thing since the defaults are fairly high and on a cluster with many pods it can reserve quite a lot of cpu and memory

**Comment by chris-ng-scmp** [comment]
This is important to set the whole cluster default resources request and limit

**Comment by ryanmt** [comment]
This sounds very similar to #216

**Comment by bkvtin** [comment]
```
vault.hashicorp.com/agent-requests-/vault.hashicorp.com/agent-limits-
```
that would be great for me to set on-demand resources for each service thank @luke-dd
