### ISSUE TITLE
Multi-pod deployment

### ISSUE THREAD

**Issue by iusergii** [hashicorp/vault-k8s#177]
**Is your feature request related to a problem? Please describe.**
My k8s apps heavily rely on Vault Secret and cannot work without it. But the current recommended installation method with [Helm Chart](https://github.com/hashicorp/vault-helm) is deployed with only 1 Pod. This creates an issue when the injector Pod relocated to another node and MutatingWebHook failurePolicy= Ignore.

**Describe the solution you'd like**
Is there any reason not to run vault-agent-injection in multiple numbers of replicas? 

**Additional context**
Raised [same](https://discuss.hashicorp.com/t/vault-k8s-multi-pod-deployment/13565) question on the discussion forum.

**Comment by tvoran** [comment]
Hi @iusergii, there is a known issue with running multiple replicas of the injector, so that's why it's limited to 1 in the chart. The issue is described and tracked here: https://github.com/hashicorp/vault-k8s/issues/141#issuecomment-685880426

**Comment by iusergii** [comment]
Hi @tvoran, thank you. Closing it in favor of https://github.com/hashicorp/vault-k8s/issues/141
