### ISSUE TITLE
Doc: Injected secrets format is in the form of a Go struct

### ISSUE THREAD

**Issue by Smana** [hashicorp/vault-k8s#18]
In the [documentation](https://www.vaultproject.io/docs/platform/k8s/injector/index.html) it is mentionned:
>If no template is provided the following generic template is used:
```
{{ with secret "/path/to/secret" }}
    {{ range $k, $v := .Data }}
        {{ $k }}: {{ $v }}
    {{ end }}
{{ end }}
```
> The rendered secret would look like this within the container:
```
$ cat /vault/secrets/foo
password: A1a-BUEuQR52oAqPrP1J
username: v-kubernet-pg-app-q0Z7WPfVNqqTJuoDqCTY-1576529094
```

However this is not really the case in my current tests:
```
kubectl exec nginx-test-87b7c7746-5cch5 -c nginx-test cat /vault/secrets/helloworld3
data: map[password:cncf username:smana]
metadata: map[created_time:2019-12-21T08:55:22.108925198Z deletion_time: destroyed:false version:1]
```

Maybe I missed something ?

**Comment by jasonodonnell** [comment]
Hello @Smana 

Some values in Vault are stored in maps, so this is the correct rendering for that type of secret (guessing this is a KV secret). The doc example uses a different secret engine (database).

The generic template just iterates over the key/values at the path. In this case it's a key "data" with a map value. The values inside can be accessed using:

```
{{ .Data.data.username }}
{{ .Data.data.password }}
```

**Comment by Smana** [comment]
Oh my bad, I didn't noticed that was a different secret engine. Thanks :)
