### ISSUE TITLE
vault namespaces support

### ISSUE THREAD

**Issue by michalschott** [hashicorp/vault-k8s#184]
I could not see anywhere in docs mentioning about vault namespaces support.

```
source: https://www.vaultproject.io/docs/agent/autoauth#namespace

mount_path (string: optional) - The mount path of the method. If not specified, defaults to a value of auth/<method type>.
namespace (string: optional) - The default namespace path for the mount. If not specified, defaults to the root namespace.
```

At the end, it looks like `authPath` can contain `vault namespace` ie. `NAMESPACE/auth/kubernetes` and it works like a charm.

**Comment by jasonodonnell** [comment]
@michalschott Namespace is already supported: https://www.vaultproject.io/docs/platform/k8s/injector/annotations#vault-hashicorp-com-namespace.

Hope that helps.

**Comment by michalschott** [comment]
@jasonodonnell exactly what I was looking for, thanks!
