### ISSUE TITLE
Pods hang in Terminating state

### ISSUE THREAD

**Issue by TamasNeumer** [hashicorp/vault-k8s#199]
**Describe the bug**
- Pods annotated with `agent-inject: "true"` sometimes hang in "`Terminating`" state. So in certain cases the webhook blocks any updates to the pod, even during termination.
- We have raised and discussed this issue with the Google Support as well and they recommended that "a sidecar injector should probably not operate on deleted pods".

**To Reproduce**
Hard... Last time we noticed this behavior when Google did a node-upgrade on the 10th of December.

**Expected behavior**
The sidecar injector should not operate on deleted pods?

**Environment**
* Kubernetes version: 
  * GKE 1.17.13-gke.2001 
  * Istio: 1.7.3
* vault-k8s version: 0.6.0

**Idea?**
- We experienced a similar issue with the gatekeeper during our node-upgrades. The single (!) gatekeeper pod had a finalizer on itself and when it was terminated, it hanged. (Circle of hell...) We upgraded gatekeeper to a newer version and here (3.1.2) it seems they run the controller-manager in HA (three pods + anti-affinity) to avoid such situations.
- The way I see vault-agent-injector doesn't use a finalizer on itself, nonetheless is it possible (and advised) to deploy it in HA in a similar fashion?

**Notes**
- I have opened this ticket because we have been experiencing this issue several times this year now. I will try to add more context whenever similar cases occur, and I also hope that the GitHub community will help gathering intelligence.
- A short-term fix is to manually remove the finalizer from the pod's yaml.

**Comment by jasonodonnell** [comment]
Hi @TamasNeumer, this is strange because our injector only looks at CREATE/UPDATE events: https://github.com/hashicorp/vault-helm/blob/master/templates/injector-mutating-webhook.yaml#L27.

I haven't seen this myself so nay additional information would be helpful. Is it the injected agents that are hanging for sure? They should be responding to shutdown signals.

**Comment by TamasNeumer** [comment]
Hi, @jasonodonnell,

Right now we are not facing this issue. Maybe we can re-label this issue and I will add information when it occurs again. (May be in a month or 3 months, we will see when it happens...)

**Comment by tvoran** [comment]
Hi @TamasNeumer, closing this issue since you stopped seeing it, but let us know if it pops up again.
