### ISSUE TITLE
Support for Vault Namespace

### ISSUE THREAD

**Issue by darren-welab** [hashicorp/vault-k8s#20]
The enterprise vault supports [vault namespaces](https://www.vaultproject.io/docs/enterprise/namespaces/index.html), but it seems that none of the annotations support it.

Something like
```yaml
vault.hashicorp.com/namespace: "ns2/secret/foo"
```

It seems that the only way to do so is by mounting my own configuration files using configmap.

Perhaps I missed something, please advise. Thanks!

**Comment by jasonodonnell** [comment]
We can add an annotation to do this.

**Comment by ecejas** [comment]
@jasonodonnell @darren-welab can you please provide an example on how to specify the vault namespace? The current vault stanza doesn't have an option for namespace (https://www.vaultproject.io/docs/agent/index.html#vault-stanza). I am not looking at the right place?  Or, this doesn't work with vault namespaces currently? Thanks!

**Comment by jasonodonnell** [comment]
There's no annotations for namespaces at this time, however you can mount a custom configuration file to do it https://www.vaultproject.io/docs/platform/k8s/injector/examples.html#configmap-example

**Comment by ecejas** [comment]
I am using that example (just config-init.hcl), but how I specify the vault namespace? I thought it would be under "vault" and that's why I checked the Vault stanza.

**Comment by jasonodonnell** [comment]
@ecejas My apologies, I was mistaken, there's not a Vault namespace setting in the configuration file (there's one under the method stanza, but it's not the Vault namespace).  It looks like only an environment variable will do, which is currently not possible with this version of Vault K8s.  We expect to have namespace support in 0.2.0, so look for that once it releases.

**Comment by malnick** [comment]
Implementation outlined in https://github.com/hashicorp/vault-k8s/issues/55
