### ISSUE TITLE
Support for injecting HTTPS_PROXY environment variable to the init and sidecar containers

### ISSUE THREAD

**Issue by danielfm** [hashicorp/vault-k8s#205]
**Is your feature request related to a problem? Please describe.**

It's a best practice to not allow connections to Vault open to all IPs (0.0.0.0/0), and instead allowlist the IP addresses that need access to Vault via ingress rules (firewall in GKE, security group in AWS, etc).

However, in my use case, the injector runs in an old Kubernetes cluster that was created without these security constraints in mind (i.e. Kubernetes nodes with external IPs, clusters with VPC native feature disabled in GKE, etc), so it becomes very difficult to control the egress IPs for injected containers, especially in auto-scaled clusters, which is the case.

**Describe the solution you'd like**

If we were able to configure the injector to set HTTPS_PROXY var to the init and sidecar containers, we would be able to make requests to Vault through a proxy with stable outgoing IP addresses, which makes it much easier to enforce the security rule described above.

This could be configured directly in the injector, so that all injected init/agent sidecars would connect to Vault via the proxy, and/or via annotations, so that we could have more control over which containers communicate to Vault via the proxy.

**Describe alternatives you've considered**

- I'm running in GKE. One alternative would be to recreate clusters with a configuration compatible with [Cloud NAT](https://cloud.google.com/nat/docs/overview) in order to have more control over the outgoing IP address for connections originating from these clusters. This ultimately would allow me to only allowlist traffic from the NAT range. However, in my case, migrating everything away from this cluster would be too much work, and I think I could benefit from Vault's features if I had a way for containers in this cluster to talk to Vault via some sort of proxy

**Additional context**

n/a

**Comment by jasonodonnell** [comment]
@danielfm seems reasonable, we'll take a look!

**Comment by danielfm** [comment]
What do you think would be the best implementation for this? Add the proxy address as an injector command line option?

If you give me some directions regarding the implementation you are more likely to accept, I can send a PR for this.

**Comment by jasonodonnell** [comment]
I think all that needs to be done is adding an annotation `vault.hashicorp.com/https-proxy`, which takes a proxy value. Then set the `HTTPS_PROXY` environment variable on the init and sidecar containers. I _think_ that's all it would take.

**Comment by jasonodonnell** [comment]
Additionally if you want to make this a global value, then yeah a new flag on Vault K8s would also be fine.

**Comment by danielfm** [comment]
Will do. Thanks!
