### ISSUE TITLE
Newline in TokenTemplate breaks token usability in some cases

### ISSUE THREAD

**Issue by jeremiahsnapp** [hashicorp/vault-k8s#207]
**Describe the bug**

The `\n` in [TokenTemplate](https://github.com/hashicorp/vault-k8s/blob/v0.7.0/agent-inject/agent/config.go#L12) breaks token usability in some cases. We have an application which reads the contents of the token file and uses it with the [vault ruby client](https://github.com/hashicorp/vault-ruby) to make API requests. The `\n` in the retrieved token value broke the API request and the vault ruby client returned the message `header field value cannot include CR/LF`.

Also, appending a `\n` to the token file is different behavior when compared to the way vault cli creates a `~/.vault-token` token file and the way vault agent writes the token to a `sink` file.

Can the `\n` be removed from `TokenTemplate`?

**Comment by tvoran** [comment]
Thanks for the report here! The newline in the injected token was removed as part of #250 since it's now injected using the same sink mechanism in vault-agent.
