### ISSUE TITLE
validating webhook

### ISSUE THREAD

**Issue by metanovii** [hashicorp/vault-k8s#208]
Without validating webhook  i always have a problem after drain node
if vault-agent-injector deployed on this node too. After migration pods starting without mutation because vault-agent-injector not started yet.

**Comment by jasonodonnell** [comment]
Hi @metanovii, doesn't a failure policy prevent pods from being deployed without mutation? https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy

We support failure policy in Vault Helm: https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L84-L89.

Additionally the injector can be deployed in HA mode, so a single injector being drained should not cause an outage of the webhook. https://github.com/hashicorp/vault-helm/blob/master/values.yaml#L30-L39

Thoughts?

**Comment by metanovii** [comment]
I will try ha mode, thanks.
