### ISSUE TITLE
Support for shutting down agent when Job ends (possibly via HTTP POST)

### ISSUE THREAD

**Issue by cpick** [hashicorp/vault-k8s#217]
**Is your feature request related to a problem? Please describe.**
We have several long-running Kubernetes batch/v1 Jobs that require credentials from an injected `vault agent`.  The token and credentials need to be renewed throughout the life of the Job and should be revoked when the Job ends (via the "vault.hashicorp.com/agent-revoke-on-shutdown" annotation).

Currently, the Jobs never finish because agent's container will continue to live on indefinitely even after the Job's "main" container finishes its work and exits.

**Describe the solution you'd like**
We'd like to have a mechanism for telling the injected vault agent to shut down.

We also run Istio in our cluster and its `istio-proxy` sidecar (which is an `envoy` proxy under the hood) has a similar issue.  The Istio project has worked around this problem by having it run a [HTTP listener](https://github.com/istio/istio/issues/15041) which gracefully exits when it receives a `POST /quitquitquit`.

Additional tooling has grown up around this convention, including the [`scuttle` helper](https://github.com/redboxllc/scuttle) which wraps the execution of the Job's "main" process and issues `POST` requests to each of the Pod's sidecars asking them to shut down.

I'd love to be able to configure the vault agent sidecar to listen for a POST on some path and cleanly shut down if/when it receives one.

**Describe alternatives you've considered**
We currently use a custom fork of the aforementioned `scuttle` command to `pkill -SIGINT vault-sidekick` but this forces us to relax our security settings by setting `shareProcessNamespace: true` and to run both the sidecar and main process under the same user.

We cannot use the "vault.hashicorp.com/agent-pre-populate-only" annotation (as suggested in [another issue](https://github.com/hashicorp/vault-k8s/issues/120#issuecomment-612442641)) because without the agent running as a sidecar the token/credentials would expire before the main Job completes (and could live beyond its completion since they're not actively revoked).

The same underlying issue has come up with `consul-k8s` and it looks like it's [adding a similar endpoint](https://github.com/hashicorp/consul-k8s/issues/162).

Envoy's [underlying endpoint](https://www.envoyproxy.io/docs/envoy/latest/operations/admin.html?highlight=quitquitquit#post--quitquitquit).

In the future this *might* be solved by Kubernetes allowing [dependencies between containers within a Pod to be specified](https://github.com/kubernetes/kubernetes/issues/65502), but that discussion has been ongoing for 2.5 years and the appropriate teams have not reached consensus on the shape/scope of the solution.

**Additional context**
I would be happy to help implement a solution if this sounds like a good idea.

**Comment by jasonodonnell** [comment]
Hi @cpick, this is an interesting feature request and I can see it being useful. Ultimately this is a Vault Agent feature, though, so I would suggest opening an issue in the Vault project: https://github.com/hashicorp/vault.

**Comment by cpick** [comment]
Thanks for the interest and suggestion @jasonodonnell; I've [requested](https://github.com/hashicorp/vault/issues/11089) this feature in `vault agent`.

Please let me know if you can think of anything else I may do to increase the chance of this feature gaining traction, it'd be a great improvement in our quality of life.

**Comment by tvoran** [comment]
Yep, I think this has been addressed as @danielhass mentioned. Thanks all!

**Comment by teomurgi** [comment]
One of the main reasons I use sidecar instead of directly using spring-vault is to avoid vendor lock-in with vault. This creates a strong dependency and would be much more preferable doing the opposite: is the agent that detects the shutdown of the main container and shuts itself down
