### ISSUE TITLE
provide JSON as the content type

### ISSUE THREAD

**Issue by dbones** [hashicorp/vault-k8s#224]
**Is your feature request related to a problem? Please describe.**

In Vault we enter this example (where the JSON structure varies between my services)
![image](https://user-images.githubusercontent.com/183849/108797570-5c9eab00-7583-11eb-8108-5c7669f6cbf7.png)

This is what the container recieves (`.Data.data`)
![image](https://user-images.githubusercontent.com/183849/108797549-56a8ca00-7583-11eb-80bc-924167230154.png)

its not JSON, (side question, what is it?), My node and .NET can work out of the box with JSON, but not this.

also, note that strings and numbers are the same i.e. `"1"` and `1` are provided as `1`

Preferably, I do not want to set up a custom format (https://www.vaultproject.io/docs/agent/template), we have already see datatype lose.

**Describe the solution you'd like**

A way to get hold of the entire secret as JSON (the way we entered it)

`Json.Data.data`

**Describe alternatives you've considered**

I have looked into a custom serializer, (however, I need to know the serialization content type of the current Data.data `map[]` so we can build a serializer) and I really do not want to own this code

use of the formatter, but this looks to be quite complex, to convert `map[]` object into a fully compliant JSON payload 

**Additional context**
the services make use of configuration libraries that fully support JSON, and the configuration vaules in vault will be complex by default (a composite of objects).

**Comment by jasonodonnell** [comment]
Hi @dbones, we've been talking about changing the default to JSON for some time and definitely think it's appropriate. The map was never useful 😄.

**Comment by dbones** [comment]
Thanks for the update, i will keep my eyes on this thread

in the mean time I have implemented a workaround (its not pretty but its simple and works for the simple usecases)

**Comment by jasonodonnell** [comment]
@dbones You're in luck, actually, because I just merged a fix in #242. I still need to add this to Vault Helm but this will be releasing mid April!
