### ISSUE TITLE
Vault Agent currently doesn't support s automatically ENV injection to POD ,  I goin to start to crate a specify sidecar for this 

### ISSUE THREAD

**Issue by jasseral** [hashicorp/vault-k8s#228]
**Is your feature request related to a problem? Please describe.**
Vault Agent currently doesn't support s automatically ENV injection to POD 

**Describe the solution you'd like**
I goin to start to crate a specify sidecar for this 

**Additional context**
Help is welcome

**Comment by yashbhutwala** [comment]
See #14, #45, #186 and https://www.vaultproject.io/docs/platform/k8s/injector/examples#environment-variable-example

**Comment by tvoran** [comment]
Thanks for pointing those out, @yashbhutwala, closing this for now.
