### ISSUE TITLE
Version support with k8s injector

### ISSUE THREAD

**Issue by virtrixke** [hashicorp/vault-k8s#231]
The API supports targeting specific secret versions (example: https://www.vaultproject.io/api/secret/kv/kv-v2#sample-request-2). Are there any plans to add this feature to the k8s injector? So a specific version of a secret can be requested using an annotation?

**Comment by bohdan-yaskov** [comment]
Try this:
```
        vault.hashicorp.com/agent-inject-secret-foo: "secrets/foo?version=1"
        vault.hashicorp.com/agent-inject-template-foo: |
          {{- with secret "secrets/foo?version=1" -}}
          ...
```

It's works for me.

**Comment by virtrixke** [comment]
Thank you bohdan! It works like a charm
