### ISSUE TITLE
Token inject annotation does not work when agent cache is enabled

### ISSUE THREAD

**Issue by dlh** [hashicorp/vault-k8s#237]
* Vault server: Vault 1.6.2, installed with hashicorp/vault 0.9.1 helm chart
* The k8s injector is configured to use hashicorp/vault-k8s:0.9.0 (`injector.image.tag=0.9.0`)

Pod annotations used:

    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-image: vault:1.7.0-rc1
    vault.hashicorp.com/agent-cache-enable: "true"
    vault.hashicorp.com/role: "bugreport"
    vault.hashicorp.com/agent-inject-token: "true"
    vault.hashicorp.com/agent-pre-populate: "true"
    vault.hashicorp.com/agent-pre-populate-only: "false"

After injection, the `/vault/secrets/token` file has contents `<no value>`, which is the output generated by [Consul Template](https://github.com/hashicorp/consul-template/blob/master/docs/templating-language.md#secret) when a map key does not exist. The [agent cache listener removed the `id` token from the  `auth/token/lookup-self` response](https://github.com/hashicorp/vault/blob/master/command/agent/cache/handler.go#L116).

I found this behavior of the agent cache listener to be a little unexpected (and undocumented). If it's intended behavior, then the k8s annotations should probably throw an error or warn when `agent-cache` is enabled with `inject-token`.

---

## The fix / work-around I'm using

I'd like to use caching, so as a work-around I've removed the `vault.hashicorp.com/agent-inject-token` annotation, and instead I use the following:

    vault.hashicorp.com/agent-inject-secret-token: "auth/token/lookup-self"
    vault.hashicorp.com/agent-inject-template-token: |
      {{- with secret "auth/token/lookup-self" -}}
        {{- file "/home/vault/.vault-token" -}}
      {{- end -}}

**Comment by jasonodonnell** [comment]
Thanks for the report @dlh, we'll take a closer look at this. Caching had significant changes in Vault 1.7 and there might have been a regression introduced.

**Comment by tvoran** [comment]
I was able to reproduce this issue, with vault-agent 1.7.0 /vault/secrets/token is indeed `<no value>`, and with 1.6.3 it's an actual token.
