### ISSUE TITLE
Custom value of AGENT_INJECT_LISTEN

### ISSUE THREAD

**Issue by HamzaZo** [hashicorp/vault-k8s#240]
We're using the vault injector in a private GKE, and I was wonder if we can use a different port of  the env`AGENT_INJECT_LISTEN` other than default value `:8080`

**Comment by jasonodonnell** [comment]
Hi @HamzaZo, how are you installing the agent injector (manual or Vault Helm)?

If you're installing manually, you can change the following values:

https://github.com/hashicorp/vault-k8s/blob/master/deploy/injector-deployment.yaml#L63-L64
https://github.com/hashicorp/vault-k8s/blob/master/deploy/injector-deployment.yaml#L85
https://github.com/hashicorp/vault-k8s/blob/master/deploy/injector-deployment.yaml#L95
https://github.com/hashicorp/vault-k8s/blob/master/deploy/injector-service.yaml#L12

If you're using Vault Helm, that's currently not supported but we would be open to adding the configurables! Please file an issue on that project if that's what you need.

**Comment by HamzaZo** [comment]
Hi @jasonodonnell 

Thanks for your reply, I create a PR for that, see [#489](https://github.com/hashicorp/vault-helm/pull/489)

**Comment by jasonodonnell** [comment]
Merged, this will be in the next release. Thanks!
