### ISSUE TITLE
Rejects admission for system namespaces

### ISSUE THREAD

**Issue by DukeyToo** [hashicorp/vault-k8s#25]
The check for system namespaces rejects the admission request, even though the annotations are not present, because the namespace check occurs before the `shouldInject` check. This results in system components being unable to deploy.

https://github.com/hashicorp/vault-k8s/blob/15de548ab08646f921ef43a8d36246a72f9bafb0/agent-inject/handler.go#L120-L124

(the `shouldInject` check should happen prior to the namespace check)

**Comment by DukeyToo** [comment]
Looks like https://github.com/hashicorp/vault-k8s/pull/24 will fix, if merged

**Comment by jasonodonnell** [comment]
This has been fixed in vault-k8s:0.1.1, please update your injector deployment.
