### ISSUE TITLE
Make the image available in Amazon ECR Public Gallery

### ISSUE THREAD

**Issue by satya-toyota** [hashicorp/vault-k8s#255]
**Is your feature request related to a problem? Please describe.**
We are hitting docker limits trying to use the docker image `hashicorp/vault-k8s` as shown 

```
Failed to pull image "hashicorp/vault-k8s:0.2.0": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Describe the solution you'd like**
It would be really great if we can have the official images pushed to [Amazon ECR Public Gallery](https://gallery.ecr.aws/?page=1) as well which will avoid the rate limiting issues and breaking of any existing applications. I see lot of other images from `hashicorp` present [here](https://gallery.ecr.aws/?page=1&searchTerm=hashicorp) but not this one. 

**Describe alternatives you've considered**
If this is not possible, we may need to pull and store the image in our own local repository. But that would be painful to upgrade the new versions as and when they are available.

**Comment by jasonodonnell** [comment]
Thanks @satya-toyota, we'll take a look into publishing our images there.

**Comment by yrsurya** [comment]
Any update on this issue as we are getting many issues for docker limits?

**Comment by yrsurya** [comment]
https://gallery.ecr.aws/hashicorp/ - I do see other images are available except vault-k8s image

**Comment by seeafish** [comment]
Any update on this? Would be really useful to break the dependency on dockerhub for Hashicorp images. I'm already pulling everything else from public ECR.
Thanks.
