### ISSUE TITLE
Please add annotation for auth path

### ISSUE THREAD

**Issue by DukeyToo** [hashicorp/vault-k8s#27]
In my opinion, a single vault cluster for multiple k8s clusters will be a common use case.

Please add an annotation for auth path. For example, if I have setup auth for 2 clusters like this:

```
vault auth enable -path=cl1 kubernetes
vault auth enable -path=cl2 kubernetes
```

...then the auth does not work because it always uses path `auth/kubernetes` and I need it to use `auth/cl1` or `auth/cl2`.

I have seen that it is possible to do this with a config map, but doing it that way removes the benefit of the simplicity provided by this project.

**Comment by DukeyToo** [comment]
Arg, once again I logged an issue for which there is already a pull request: https://github.com/hashicorp/vault-k8s/pull/23 will fix my issue

**Comment by jasonodonnell** [comment]
#23 will address this issue.  Will be merged once the holiday shutdown is over.
