### ISSUE TITLE
webhook should write typed AdmissionReview response with GVK set

### ISSUE THREAD

**Issue by ravilr** [hashicorp/vault-k8s#294]
**Describe the bug**
Running the vault-injector with this webhookconfiguration https://github.com/hashicorp/vault-k8s/blob/v0.12.0/deploy/injector-mutating-webhook.yaml#L12 leads to all webhook requests failing with below error in kube-apiserver logs:

`failed calling webhook \"vault.hashicorp.com\": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind="`

by changing the order of `admissionReviewVersions: ["v1beta1", "v1"]`  fixes the above error on kube-apiserver version < v1.22.

**To Reproduce**
- Deploy vault-agent-injector v0.12.0 with webhookconfiguration having `admissionReviewVersions: ["v1", "v1beta1"]` and `failurePolicy: fail`. All pod creation requests fails with above error.

**Expected behavior**
webhook must return a well formed AdmissionReview response including apiVersion and kind (GVK). And to support multiple admissionReviewVersions configured in webhookconfiguration, webhook should look at the GVK typemeta of the incoming AdmissionReview request and send the response with Typemeta set to the same GVK as the one in the admission request. 

**Environment**
* Kubernetes version: v1.21.4
* vault-k8s version: v0.12.0

**Additional context**
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.10.0/pkg/webhook/admission/http.go#L79 is relevant.

**Comment by tvoran** [comment]
Hi @ravilr, thanks for looking into this! We've done most of our testing with the templates in [vault-helm](https://github.com/hashicorp/vault-helm/blob/8932c372b75be87540f30b194eac587c85b4a3d4/templates/injector-mutating-webhook.yaml#L18-L20), which has the ordering of `admissionReviewVersions: ["v1beta1", "v1"]`, so I'm guessing that's why we haven't run into this in testing.

Would it be sufficient to just change the ordering here in the vault-k8s deployment yaml as well?

**Comment by ravilr** [comment]
> Would it be sufficient to just change the ordering here in the vault-k8s deployment yaml as well?

admissionReview API was promoted to `admission.k8s.io/v1` in [Kubernetes v1.16](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/CHANGELOG/CHANGELOG-1.16.md#api-changes) and v1beta1 was deprecated. but, both v1 and v1beta1 admissionReview objects are supported as of v1.22.  In the interest of moving away from deprecated v1beta1, it is better for vault-k8s webhook handler to properly support admissionReview.v1 request/response's.

I made a PR https://github.com/hashicorp/vault-k8s/pull/296 updating the webhook handler to handle both v1 and v1beta1 versions correctly as expected.
