### ISSUE TITLE
k8s auth method returning 403s 

### ISSUE THREAD

**Issue by alexkim-avant** [hashicorp/vault-k8s#308]
Getting the following message from the vault-agent-init container:
```
2021-11-22T17:45:28.794Z [INFO]  auth.handler: authenticating
2021-11-22T17:45:58.799Z [ERROR] auth.handler: error authenticating:
  error=
  | Error making API request.
  | 
  | URL: PUT https://<REDACTED>/v1/auth/kubernetes/login
  | Code: 403. Errors:
  | 
  | * permission denied
   backoff=4.65s
```

Deployed the vault-agent-injector through Helm chart version 0.17.1 with just the externalVaultAddr overwritten in the default namespace. I followed the instructions in this guide: https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes using the vault service account autogenerated by the Helm install. Then, in a new namespace, I created a service account `vault-auth` and in my deployment I set `serviceAccountName: vault-auth`. My vault auth and role config look like this:

```
vault write auth/kubernetes/config \
        token_reviewer_jwt="$TOKEN_REVIEW_JWT" \
        kubernetes_host="$KUBE_HOST" \
        kubernetes_ca_cert="$KUBE_CA_CERT" \
        issuer=https://oidc.eks.us-east-2.amazonaws.com/id/<REDACTED>
```
```
vault write auth/kubernetes/role/secret_injector \
        bound_service_account_names=vault-auth \
        bound_service_account_namespaces=\* \
        policies=app_secret_injector \
        ttl=24h
```
I am running my k8s cluster on EKS on version 1.21 and vault externally on version 1.8.5.

**Comment by alexkim-avant** [comment]
Resolved via adding new SGs for inbound traffic.

**Comment by wanghongda-0624** [comment]
hi what is SGs

**Comment by tide-jamiegwatkin** [comment]
Just to add more detail because I was stuck on this, when using HCP you need to take the CIDR of the HCN that Vault is installed in and then exempt it in the security group of the EKS cluster.

It actually says this in the documentation at:

```EKS cluster security group must allow traffic from the HCP Vault CIDR range. If your EKS cluster endpoint uses port 443, create a security group rule to allow ingress traffic from HCP Vault to the primary EKS cluster security group.
``` 

Which I missed at the time.
