### ISSUE TITLE
Allow setting ephemeral-storage requests and limits for injected container

### ISSUE THREAD

**Issue by thechristschn** [hashicorp/vault-k8s#310]
**Is your feature request related to a problem? Please describe.**
In our cluster we deployed LimitRanges with default requests and limits for cpu, memory and ephemeral-storage.

The cpu and memory requests and limits can be configured with environment variables on the injector or annotations at the target resource. But for ephemeral-storage this isn't possible.

While our defaults in the LimitRange are good for the application containers, they are way too high for the vault-agent.
We have a multi-tenant cluster where we set LimitRanges and ResourceQuotas for all Namespaces. With the introduction of vault-agent-injector, we got the problem, that all those high defaults which are applied to the vault-agents, are depleting the quota.

Because we have many different user, we can't just change the defaults in the LimitRange to fit the vault-agent and would rather configure the values for the vault-agent container explicitly.

**Describe the solution you'd like**
Add a possibility to set ephemeral-storage requests and limits for the injected vault-agent and vault-agent-init containers. This should be possible via environment variables on the injector or via annotation on the pod.

The annotations would be `vault.hashicorp.com/agent-requests-ephemeral-storage` and `vault.hashicorp.com/agent-limits-ephemeral-storage`.

The environment variables would be `AGENT_INJECT_EPHEMERAL_STORAGE_REQUEST` and `AGENT_INJECT_EPHEMERAL_STORAGE_LIMIT`.

It should also be possible to configure the environment variables in the helm chart, but that would be a follow-up feature in the vault-helm repository.

**Describe alternatives you've considered**
We could change the defaults in the LimitRange, but that would require to adjust all other deployments in the cluster.

**Comment by hsimon-hashicorp** [comment]
Thanks for submitting this request for enhancement! I'll get it triaged as soon as I can. :)

**Comment by tomhjp** [comment]
Should be resolved by #360 which is now merged. Thanks!
