### ISSUE TITLE
Injecting secrets into specific containers

### ISSUE THREAD

**Issue by dmitrytretyakov** [hashicorp/vault-k8s#311]
**Is your feature request related to a problem? Please describe.**
For now, the agent injects secrets into all containers.
As we use Vault for sensitive data it's not good to share secrets between all of the containers in the pod.
For example, I don't want to share admin creds from DB to monitoring tools (e.g. prometheus-exporter)
It increases the chance to compromise a system

**Describe the solution you'd like**
It would be nice to have a way to limit the list of containers in which are required to be injected.
Via adding annotation for this feature

**Comment by tvoran** [comment]
Hi @dmitrytretyakov thanks for raising the issue! Is this similar to #236? There's also a proposed PR solution for it in #245.

**Comment by dmitrytretyakov** [comment]
Hi, @tvoran !
yes, that's what we need
Subscribed for PR, thanks!
