### ISSUE TITLE
Allowing mounting of secrets to locations other than /vault/secrets

### ISSUE THREAD

**Issue by fire833** [hashicorp/vault-k8s#312]
According to current documentation, secrets that are injected by the agent injector are injected into /vault/secrets within the pod filesystem. Would it be possible to add an annotation such as `vault.hashicorp.com/agent-inject-secret-foo-filesystem-location: /etc/something/somewhere` to specify a custom location where the specified secret/rendered template could be mounted for legacy applications? This may be frivolous and was already implemented, but based on what I have seen with issues such as #84, they don't necessarily allow you to specify a custom mount location for secrets that are to be injected, whether raw or with a template. Please let me know if this is possible/already implemented, I'm curious.
Thanks

**Comment by tim-sendible** [comment]
`vault.hashicorp.com/secret-volume-path`

https://www.vaultproject.io/docs/platform/k8s/injector/annotations

**Comment by fire833** [comment]
Ah
