### ISSUE TITLE
Healchecks via https are succefull in case of certificate issue

### ISSUE THREAD

**Issue by wildermesser** [hashicorp/vault-k8s#318]
I discovered strange vault injector behavior. I use liveness probe like:
```
Liveness:   http-get https://:8080/health/ready delay=30s timeout=30s period=30s #success=1 #failure=3
```
After some very strage events in may k8s cluster, vault injector failed 3 probes and was restarted by kubelet:
```
 [ERROR] handler: http: TLS handshake error from 10.0.216.118:51410: EOF
 [ERROR] handler: http: TLS handshake error from 10.0.216.118:37002: EOF
 [ERROR] handler: http: TLS handshake error from 10.0.216.118:55394: EOF
```
It is still normal and expected behavior. But after restart vault injector could not read certificate from filesystem with endless logs like:
```
handler.certwatcher: Could not load TLS keypair: tls: failed to find any PEM data in certificate input. Trying again...
handler.certwatcher: Could not load TLS keypair: tls: failed to find any PEM data in certificate input. Trying again...
...
```
I have no idea how it can be possible. I can read cert and key file inside vault injector container without problem. May be some memory issue in k8s node...
In any way, tls in vault injector is broken, but `curl https://pod_address:8080/health/ready` return 204 code as correctly working instance.
If healthcheck request fail in this scenario, kubelet will restart container and vault injector starts working normally.

May be add some try threshold for tls issue? And after threshold's excess health check endpoint will response error code.

Application deployment:

**Environment**
* Kubernetes version: 1.20.11
  * Baremetal
* vault-k8s version: 0.14.0

**Comment by RemcoBuddelmeijer** [comment]
What is your setup when it comes to the certification source? Do you define a cert and key file or do you let leader election take care of this for you?

**Comment by wildermesser** [comment]
Key and cert are generated "manually" (using CA built-in k8s) and stored in Secret resource. Vault-inject deployed with ENVs:
```
         - name: AGENT_INJECT_TLS_CERT_FILE                                                                                                                  
           value: /etc/webhook/certs/tls.crt                                                                                                                 
         - name: AGENT_INJECT_TLS_KEY_FILE                                                                                                                   
           value: /etc/webhook/certs/tls.key  
```
Such setup works fine almost every time. I checked those hundreds of times. So the issue is incorrect https probes response in case of TLS issue despite TLS issue's reason

**Comment by swenson** [comment]
The `handler.certwatcher: Could not load TLS keypair: tls: failed to find any PEM data in certificate input. Trying again...` error is for an internal key and CA that are generated by `vault-k8s`. It shouldn't affect the healthcheck if `AGENT_INJECT_TLS_CERT_FILE` and `AGENT_INJECT_TLS_KEY_FILE` are set, since those certificates will be loaded (and presumably, used by liveness probe).

I think @RemcoBuddelmeijer is correct, and that this is related to the usually quick, but confusing error, on startup when TLS certificates haven't generated but HTTP probes have come.

I will work on a fix for that, I think.
