### ISSUE TITLE
\n in templates breaks some software 

### ISSUE THREAD

**Issue by mindfulmonk** [hashicorp/vault-k8s#319]
Hello!

I've recently hit an issue trying to use `vault.hashicorp.com/agent-inject-token` with Harness, where it couldn't handle the new line and would error out. If one was to write curl scripts with the token you would also have to strip the \n when reading in the token.

https://github.com/hashicorp/vault-k8s/blob/286c36fcff05636581cdedcc4b2686da138ca4bc/agent-inject/agent/config.go#L12

If you look at the token generated by vault itself on disk it does not have a new line either. Could you please let me know the purpose of \n in this template(is it just to keep it POSIX?) and if it is ok to raise a PR to remove it?

**Comment by tvoran** [comment]
I'm curious what version of vault-k8s you are using? This sounds like an issue that was fixed in v0.10.1 (https://github.com/hashicorp/vault-k8s/blob/main/CHANGELOG.md#0101-may-25-2021) by #250.

**Comment by mindfulmonk** [comment]
Cheers, good catch we were on 0.9.0
