### ISSUE TITLE
Agent skips TLS verification by default

### ISSUE THREAD

**Issue by xntrik** [hashicorp/vault-k8s#33]
As per 3rd party report
https://github.com/hashicorp/vault-k8s/blob/8f3a6118fb8b640e9439523f758703973dbdd472/agent-inject/agent/annotations.go#L228

**Comment by jasonodonnell** [comment]
The fix has been merged, test coverage was added to ensure this stays fixed and `vault-k8s:0.1.2` was released.

**Comment by xntrik** [comment]
Thanks to @fischerman for reporting the issue!
