### ISSUE TITLE
Admission controller registration is invoked every second

### ISSUE THREAD

**Issue by jimsnab** [hashicorp/vault-k8s#332]
**Describe the bug**
The `certWatcher` is calling kubernetes api once per second to patch the mutating webhook config, even when no certificate change takes place. This results in a lot of log spam and extra cloud provider charges (even if they may be relatively small).

https://github.com/hashicorp/vault-k8s/blob/c25fcef11201a25d74f73cf62f2006b05997f826/subcommand/injector/command.go#L328

The certWatcher should notice nothing has changed since its last cert update and avoid invoking the api unnecessarily.

**To Reproduce**
1. Run the sidecar
2. Examine activity such as kubernetes controller logs

**Comment by swenson** [comment]
Thanks for reporting this. It is an issue we had been thinking about for a while. I submitted a PR to potentially fix this in #336.
