### ISSUE TITLE
Support for periodic updating of secrets

### ISSUE THREAD

**Issue by talarczykco** [hashicorp/vault-k8s#39]
According to [Agent Sidecar Injector](https://github.com/hashicorp/vault/blob/04102533fc926262824cb643d548ec6dcb98c645/website/source/docs/platform/k8s/injector/index.html.md#mutations) docs, "The init container will prepopulate the shared memory volume with the requested secrets prior to the other containers starting. The sidecar container will continue to authenticate and render secrets to the same location as the pod runs."

This leads me to believe the sidecar will automatically update the shared mount with the result of new or changed passwords from the source Vault as they change over time. However, this has not proven to be the case in my setup, and I can find no documentation to suggest there is a configuration for setting a periodic password refresh (e.g., a setting to re-sync all passwords every 15 minutes.)

Is this possible now, or on the roadmap? I can delete pods and have the shared mount repopulated with updated password values (or just kill the vault-agent container to the same effect) but I would prefer to take advantage of a configurable value handled cleanly by the sidecar if there was one.

**Comment by frittentheke** [comment]
Did you set a TTL for the secret then @talarczykco ? How would the client otherwise know that the secret is not static.

**Comment by jasonodonnell** [comment]
@frittentheke is correct, you need to adjust the TTL of the secret.

**Comment by talarczykco** [comment]
Thanks @frittentheke and @jasonodonnell! Indeed, setting a TTL on my secret allowed the sidecar to update the injected value with subsequent changes.

To modify the [documentation](https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/) example for clarity:

```
vault kv put secret/helloworld username=foobaruser password=foobarbazpass ttl=15m
```
