### ISSUE TITLE
Webhook certificates to be managed by an external component like cert manager

### ISSUE THREAD

**Issue by kishoregv** [hashicorp/vault-k8s#414]
**Is your feature request related to a problem? Please describe.**
Currently, the webhook create and patch the mutating webhook config with the cerificate data. We need possibility to manage certificates from out side the webhook some thing like a cert manager to handle the certifcates for the webhook.

**Describe the solution you'd like**
Give a flag to allow the webhook code to use certificates to be managed by cert manager.

**Describe alternatives you've considered**
No, other alternative

**Comment by tvoran** [comment]
Hi @kishoregv, this can be done currently as described in these docs:
* self-signed certs: https://developer.hashicorp.com/vault/docs/platform/k8s/helm/examples/injector-tls
* cert manager: https://developer.hashicorp.com/vault/docs/platform/k8s/helm/examples/injector-tls-cert-manager
