### ISSUE TITLE
Support structured json logging

### ISSUE THREAD

**Issue by lalbers** [hashicorp/vault-k8s#47]
Currently, only environmental settings for _log_level_ are available. 
It would be great if json logging get's supported, particularly as _hclog_ supports it.

**Comment by jasonodonnell** [comment]
Reasonable request, I think we could add a configurable for this!

**Comment by frittentheke** [comment]
This is really great @lalbers !

Looking at the field names there is the "@" sign in front. Not that this breaks anything, but in the context of shipping stuff to an ElasticSearch this sometime needs extra treatment. Especially when looking at "@timestamp" ...

```
{"@level":"info","@message":"Request received","@module":"handler","@timestamp":"2020-01-21T08:43:25.828108Z","Method":"POST","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/mutate","RawPath":"","ForceQuery":false,"RawQuery":"timeout=30s","Fragment":""}}
{"@level":"debug","@message":"checking if should inject agent..","@module":"handler","@timestamp":"2020-01-21T08:43:25.828687Z"}
{"@level":"debug","@message":"checking namespaces..","@module":"handler","@timestamp":"2020-01-21T08:43:25.828707Z"}
{"@level":"debug","@message":"setting default annotations..","@module":"handler","@timestamp":"2020-01-21T08:43:25.828716Z"}
{"@level":"debug","@message":"creating new agent..","@module":"handler","@timestamp":"2020-01-21T08:43:25.828739Z"}
{"@level":"debug","@message":"validating agent configuration..","@module":"handler","@timestamp":"2020-01-21T08:43:25.828790Z"}
```


Is there maybe an easy way to remove those?

**Comment by tvoran** [comment]
Closing, since json logging support was added in v0.5.0: https://github.com/hashicorp/vault-k8s/blob/master/CHANGELOG.md#030-march-5th-2020
