### ISSUE TITLE
Could you please release arm and arm64 images?

### ISSUE THREAD

**Issue by mcanevet** [hashicorp/vault-k8s#64]

**Comment by moikot** [comment]
Second that!

**Comment by moikot** [comment]
second that

**Comment by moikot** [comment]
Just in case if someone needs it now, a repo for building linux/amd64, linux/arm64, linux/386, linux/arm/v6 https://github.com/moikot/vault-k8s-image

**Comment by giolekva** [comment]
+1, needed for RPi deployments

**Comment by mousiefasil** [comment]
+1

**Comment by ahuffman** [comment]
Really strange you're building the vault image for ARM/ARM64, but not the injector.  It would be awesome if this got another set of 👀 !  Thanks.

**Comment by moikot** [comment]
@ahuffman my dear friend, what I find really strange is that your hints that I might have some intents to missuse the image I'm building. No, it's not strange, it's a pure insult. Have you ever commented the same about other security critical repositories? Or any repositories for that matter? Probably not, is it because I have a rrussina name? Probably it is.

**Comment by mousiefasil** [comment]
@moikot I think, correct me if I am wrong, but that the statement of  @ahuffman is with respect to the fact that this repo produces artifacts of vault for all arch but the injector is only build for amd64 arch. 
I personally am currently using your injector artifact, but in general I prefer that the ones you code it build the artifact.

**Comment by ahuffman** [comment]
@moikot I think you misunderstood my comment.  I'm simply stating I think it's odd that the vault:1.4.2 container is built for all architectures, but the hashicorp/vault-k8s:0.4.0 images are not built for all architectures.  I was hoping to get the hashicorp org to take a look at building the container image for ARM64.

**Comment by moikot** [comment]
@ahuffman I have to apologize here for jumping to conclusions too quickly. I've forgotten what I'm actually building since I stopped using it. And indeed it is Vault-k8s, not a Vault image.

**Comment by yuliyan-cloudders** [comment]
I was trying to install vault-k8s on arm64 and I found this guy that has rebuilt the image:

https://hub.docker.com/r/moikot/vault-k8s

I wonder why really there is no arm artifact since the other images are cross-compatible with ARM

**Comment by JeffUnderhill** [comment]
Any updates on this issue? given the Arm64 vault binary exists having vault-k8s packaged for Arm64 enables consumption consistent with other platform architectures. It's good a workaround already exists from moikot above but consuming an official image is clearly preferable for prod environments.

**Comment by tvoran** [comment]
Hi folks, as of 0.9.0 we're now publishing Arm binaries and images. Cheers!

https://hub.docker.com/r/hashicorp/vault-k8s/tags?page=1&ordering=last_updated
https://releases.hashicorp.com/vault-k8s/0.9.0/
