### ISSUE TITLE
EKS/Weave Net CNI webhook issue

### ISSUE THREAD

**Issue by paulwitt** [hashicorp/vault-k8s#72]
We're running on EKS and using the Weave Net CNI provider.  Ran into an issue where the webhook couldn't reach the service.  Cloudwatch showed this error:

`Failed calling webhook, failing open vault.hashicorp.com: failed calling webhook "vault.hashicorp.com": Post https://vault-injector-svc.vault.svc:443/mutate?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Turns out it has to do with the webhooks running on the managed master and not respecting the CNI provider on the nodes.  I had to set the deployment to have `hostNetwork: true`.

Hopefully this saves someone else from some pain.

**Comment by pksurferdad** [comment]
Hi @paulwitt where is the hostNetwork config? I'm trying to run vault on EKS as well and the injector fails to initialize in the deployment

**Comment by paulwitt** [comment]
> Hi @paulwitt where is the hostNetwork config? I'm trying to run vault on EKS as well and the injector fails to initialize in the deployment

I'm not sure I understand the question (probably because it's the weekend and I shut this part of my brain off on the weekend) but by host network I mean simply to tell k8s that the pod needs to use whatever network your EC2s are using.  In our case it's a 10. subnet.  This is just done by using `hostNetwork: true` in your deployment yaml.  All you're looking for is the IP of your pod to match the IP of your EC2 (`kubectl get pods -o wide`)

Does that answer your question?

**Comment by pksurferdad** [comment]
> > Hi @paulwitt where is the hostNetwork config? I'm trying to run vault on EKS as well and the injector fails to initialize in the deployment
> 
> I'm not sure I understand the question (probably because it's the weekend and I shut this part of my brain off on the weekend) but by host network I mean simply to tell k8s that the pod needs to use whatever network your EC2s are using. In our case it's a 10. subnet. This is just done by using `hostNetwork: true` in your deployment yaml. All you're looking for is the IP of your pod to match the IP of your EC2 (`kubectl get pods -o wide`)
> 
> Does that answer your question?

thx for responding @paulwitt.  my issue turned out to be something else.  i'm good now.

**Comment by tvoran** [comment]
Looks like this was added in hashicorp/vault-helm#471
