### ISSUE TITLE
Support running Vault Agent cache in sidecar container

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/vault-k8s#73]
https://www.vaultproject.io/docs/agent/caching/index.html

**Comment by hamishforbes** [comment]
It would be helpful to have an annotation that enables a `listener {}` and `cache {}` block in the sidecar agent.

Something like

```
vault.hashicorp.com/agent-listen: bool (default: false)
vault.hashicorp.com/agent-listen-tls-disable: bool (default: true)
vault.hashicorp.com/agent-listen-address: string (default: 127.0.01:8200)
vault.hashicorp.com/agent-cache-auto-auth: bool (default: false)
```

I'm migrating a number of services onto k8s which previously were able to access Vault via an agent listening on plain HTTP bound to 127.0.0.1.

I can reproduce this in k8s but only by using the configmap method to add a listener, which is ok but very verbose and repetitive for many services

**Comment by lawliet89** [comment]
#132 implements this. But I have kept TLS disabled always for now because there is no way to mount arbitrary volumes now.
