### ISSUE TITLE
Can we use vault-k8s if Vault server doesn't inside kubernetes cluster ? 

### ISSUE THREAD

**Issue by vankhoa011** [hashicorp/vault-k8s#76]
Hi all, 
We have Vault server was installed in VMs. And we have Kubernetes cluster, and we want to use vault-k8s to get secret from Vault server which is outside K8S cluster . 

Do we have any document how to do that ?  Thank you in advance.

**Comment by tvoran** [comment]
Hi @vankhoa011, we're working on documentation for this kind of setup, and in the meantime you can find the info in https://github.com/hashicorp/vault-k8s/issues/15.

**Comment by vankhoa011** [comment]
@tvoran : Thanks for your reply. I will take a look at this document.

**Comment by tvoran** [comment]
Also, the vault-helm chart (https://github.com/hashicorp/vault-helm) has an option for configuring the vault-k8s injector to use an external vault server. There is also a learn guide describing it here: https://learn.hashicorp.com/vault/getting-started-k8s/external-vault

Closing this for now; do let us know if you have further questions!
