### ISSUE TITLE
Support projected ServiceAccount volumes

### ISSUE THREAD

**Issue by dippynark** [hashicorp/vault-k8s#78]
The current implementation uses the workloads normal ServiceAccount token at `/var/run/secrets/kubernetes.io/serviceaccount/token`. This token does not expire and allows access to the Kubernetes API allowing Vault to impersonate the workload.

Support for [projected ServiceAccount volumes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) would allow the token to be rotated and would mean that if the token were intercepted it could only be used to authenticate to Vault (rather than have wider impacts against the Kubernetes API).

**Comment by davidmontoyago** [comment]
Hi there, the related PR sadly went stale.

Is there currently a workaround to specify the token `aud`ience without using a projected SA volume? I'm afraid without support for a projected volume people would be forced to disable JWT issuer validation ( See: [disable_iss_validation](https://www.vaultproject.io/api/auth/kubernetes#disable_iss_validation)). Is this what other vault practitioners out there are doing?

**Comment by dippynark** [comment]
@davidmontoyago unfortunately Kubernetes only supports custom `aud` field with a projected volume. I've rebased the PR again so hopefully can get it merged
