### ISSUE TITLE
Metadata annotations are limited to 63 char, filename is embedded in annotation

### ISSUE THREAD

**Issue by sbeaulie** [hashicorp/vault-k8s#88]
I tried creating a filename that is longer than `foo` and I'm getting this error returned when creating the pods:
```metadata.annotations: Invalid value: "vault.hashicorp.com/agent-inject-secret-.aws_us_east_aws_secret_key.pem": name part must be no more than 63 characters```

While I understand this to be a k8s limitation (probably), the fact that the hashicorp prefix is 40 char long for `vault.hashicorp.com/agent-inject-secret-` and 42 char long for `vault.hashicorp.com/agent-inject-template-` it leaves very little space for the filename.

It also feels like bad practice to have the filename embedded in an annotation name.

**Proposed Solution**: 
Annotation values seem to accept arbitrarily long data sequence (I don't know the limit but my template definitions are long). 
Do not embed the filename in the annotation name, but rather in the value. 
Add another annotation for the expected filename and use that to create the file on disk. 

Example configuration after the change:
```
vault.hashicorp.com/agent-inject-secret-foo: "vault/secret/stored" # foo here is a unique identifier, not the filename
vault.hashicorp.com/agent-inject-secret-filename-foo: "my/aws/region/is/very/long/and/someone/loaded/the/pem/uuid/aaa-fffff-ggggg-eeee-awd-ffdgfdg-gfdgfdgfdg.pem" # stored in the value
vault.hashicorp.com/agent-inject-template-foo: "" # no change here
```

That way it has the extra advantage that the filename can contain a directory "/" delimiter since the annotation name can't.

I understand this is not a fun issue report to get as the solution above would be a breaking change for current users. As a compromise you could keep the current limited behavior, and intead use a new annotation for this split location / filename scenario:

```
vault.hashicorp.com/agent-inject-location-foo: "vault/secret/stored" # foo here is a unique identifier, not the filename. the value is the location of the vault secret
vault.hashicorp.com/agent-inject-filename-foo: "my/aws/region/is/very/long/and/someone/loaded/the/pem/uuid/aaa-fffff-ggggg-eeee-awd-ffdgfdg-gfdgfdgfdg.pem" # stored in the value
vault.hashicorp.com/agent-inject-template-foo: "" # no change here
```

the old (deprecated) way `vault.hashicorp.com/agent-inject-secret-<my_filename>` used by itself would still work but `<my_filename>` would be limited to 21 char if there is a template and 23 if there isn't one.

**Comment by smitthakkar96** [comment]
I hit the same road block few weeks ago, I needed a quick workaround so I started using configmaps

**Comment by angelo-wm** [comment]
Has there been any progress regarding the PR for this issue?
