### ISSUE TITLE
Vault agent sidecar should be able to handle different location than /vault/secrets

### ISSUE THREAD

**Issue by JnMik** [hashicorp/vault-k8s#92]
Hello guys !

Is your feature request related to a problem? Please describe.
When using the vault agent sidecar to inject secrets file into a container, it's always trouble because I can't specify my own location, i'm stuck with the default /vault/secrets.

Describe the solution you'd like
I would like to be able to tell the vault-agent-sidecar where to drop the file.
I would expect an annotation looking like this.
"vault.hashicorp.com/agent-inject-secret-filepath" = "/filepath/where/I/want/the/file/"

Describe alternatives you've considered

Considering it's for java app with springboot...

Overriding environment variable SPRING_CONFIG_LOCATION to add another location, but I could be de-sync with the project paths if a developer updates the value in their yaml file and forget to update environment variable.

Force the container to boot on a custom bootstrap.sh script, where I would copy the file to the right location before starting the java app. Not very elegant.

Suggest developers that I will add file:/vault/secrets path in their spring config location setting (it's what I choose as my workaround for now). But it feels cheap to alter their app core settings to provide secrets.

What do you think ?
Cheers

**Comment by jasonodonnell** [comment]
Hi @JnMik ,

This feature has already been merged and will be in the next release later this week: https://github.com/hashicorp/vault-k8s/pull/71

Hope that helps!
